Watch_Hub/urls.py
from django.contrib import admin
from django.urls import include, path


from Watch_Hub.views import Maintenance, Home
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='Watch-Hub-Home'),
    path('manutenzione/', Maintenance.as_view(), name="maintenance"),
    path('blog/', include('blog.urls')),
    path('register/', user_views.register, name='user-create'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

blog/urls.py
from django.urls import path
from django.views.generic import UpdateView

from . import views
from blog.views import WatchDetail, WatchList, create_watch, ConditionView, LikeView, watchSearch, UpdateWatch, \
    MaisonListView, MaisonDetailView

app_name = 'blog'

urlpatterns = [
    path('<int:pk>/detail/', WatchDetail.as_view(), name="blogPostDetail"),
    path('list/', WatchList.as_view(), name="blogPostList"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('update/<int:pk>/', UpdateWatch.as_view(), name="blogPostUpdate"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('like/<int:pk>', LikeView, name="like_post"),
    path('search/', views.watchSearch, name="watchSearch"),
    path('condizione/<str:condition>', ConditionView, name="conditionWatch"),
    path('categoria_watch/', views.conditionListView, name='conditionWatchList'),
    path('maison_list/', MaisonListView.as_view(), name='MaisonList'),
    path('maison_detail/<int:pk>/', MaisonDetailView.as_view(), name='MaisonDetail'),
    path('favorite/', views.favorite_watch_view, name='favoriteWatch'),
    path('suggestion/', views.watch_suggestion, name='suggestionWatch'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.


class Maison(models.Model):
    maison = models.CharField(max_length=20, default=None)

    def __str__(self):
        return f'{self.maison}'

class Condition(models.Model):
    condition = models.CharField(max_length=20, default='New')

    def get_absolute_url(self):
        return reverse('blog:blogPostDetail', args=(str(self.id)))
        #return reverse('Watch-Hub-Home')

    def __str__(self):
        return f'{self.condition}'


class Watch(models.Model):
    maison = models.ForeignKey(Maison, default=None, on_delete=models.CASCADE)
    model = models.CharField(max_length=40, default='')
    reference = models.CharField(max_length=40, default='')
    movement = models.CharField(max_length=40, default='')
    condition = models.CharField(max_length=20, default='New')
    owner = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    date_creation = models.DateField(null=True)
    photo = models.ImageField(default='watch_cover_default', upload_to='static/image/')
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()


    def __str__(self):
        return f'{self.model} - {self.pk}'

    def get_absolute_url(self):
        return reverse('blog:blogPostDetail', args=(str(self.id)))
        #return reverse('Watch-Hub-Home')

blog/forms.py
from django import forms

from blog.models import Watch, Maison, Condition
from django.contrib.auth.models import User

choices = Condition.objects.all().values_list('condition','condition')

choice_list = []
for item in choices:
    choice_list.append(item)


class WatchCreate(forms.ModelForm):
    class Meta:
        model = Watch
        fields = ('maison', 'model', 'movement', 'condition', 'owner', 'reference', 'price', 'photo', )
        widgets = {
            'cond' : forms.Select(choices = choice_list, attrs={'class':'form-control'}),
        }


class MaisonForm(forms.ModelForm):
    class Meta:
        model = Maison
        fields = ('maison',)
        labels = {
            'maison': 'Maison Name',
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from numpy import mean

# Create your views here.
from django.views.generic import DetailView, ListView, UpdateView

from blog.forms import WatchCreate, MaisonForm
from blog.models import Watch, Maison, Condition


@login_required()
def LikeView(request, pk):
    post = get_object_or_404(Watch, id=request.POST.get('post_id'))
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:blogPostDetail', args=[str(pk)]))


class WatchDetail(DetailView):
    model = Watch
    template_name = 'blog/blogPost/detail.html'

    def get_context_daya(self, *args, **kwargs):
        context = super(WatchDetail, self).get_context_data(**kwargs)
        stuff = get_object_or_404(Watch, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        return context

class WatchList(ListView):
    model = Watch
    template_name = 'blog/blogPost/home_view.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Condition.objects.all()
        context = super(WatchList, self).get_context_data(**kwargs)
        context["cat_menu"] = cat_menu
        return context

    def get_queryset(self):
        result = super(WatchList, self).get_queryset()
        query = self.request.GET.get('order')
        if query:
            if query == 'maison' or query == 'model' or query == "owner":
                result = Watch.objects.all().order_by(query)
        else:
            result = Watch.objects.all()
        return result


class MaisonDetailView(DetailView):
    model = Maison
    template_name = 'blog/blogPost/maison_detail.html'


class MaisonListView(ListView):
    model = Maison
    template_name = 'blog/blogPost/maison_list.html'

def conditionListView(request):
    condition_watch_list = Condition.objects.all()
    return render(request, 'blog/blogPost/condition_list.html', {'condition_watch_list': condition_watch_list})

@login_required
def create_watch(request):
    if request.method == 'POST':
        form = WatchCreate(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('Watch-Hub-Home')
    else:
        form = WatchCreate()

    return render(request, 'blog/blogPost/insert_watch.html', {'form': form})


def watchSearch(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        watch_list = Watch.objects.filter(model__contains=searched)
        return render(request, 'blog/blogPost/watch_search.html', {'searched': searched, 'watch_list':watch_list})
    else:
        return render(request, 'blog/blogPost/watch_search.html', {})


def ConditionView(request, condition):
    condition_watch = Watch.objects.filter(condition=condition)
    return render(request, 'blog/blogPost/watch_list.html', {'condition':condition, 'condition_watch': condition_watch})

class UpdateWatch(UpdateView):
    model = Watch
    template_name = 'blog/blogPost/update_watch.html'
    fields = ['condition', 'price', 'photo']

    def get_context_data(self, *args, **kwargs):
        cat_menu = Condition.objects.all()
        context = super(UpdateWatch, self).get_context_data(**kwargs)
        context["cat_menu"] = cat_menu
        return context


@login_required
def maison_create(request):
    if request.method == 'POST':
        form = MaisonForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('<script type="text/javascript">window.close()</script>')
        else:
            form = MaisonForm()

        return render(request, 'blog/blogPost/maison_create.html', {'form': form})


def favorite_watch_view(request):
    list_like = []

    for watch in Watch.objects.all():
        if watch.likes.filter(username=request.user.username).exists():
            if watch not in list_like:
                list_like.append(watch)

    context = {
        'list_like': list_like
    }

    return render(request, 'blog/blogPost/favorite.html', context)


def watch_suggestion(request):
    sugg_watch = []
    maison_like = []
    watch_like = []
    w_price = 0
    watch_price = []

    # dai miei orologi preferiti inserisco agli orologi suggeriti anche quelli con prezzo simile
    w_price = mean([Watch.price for Watch in watch_like])

    #inserisco la maison di un orologio a cui hai messo mi piace e non è ancora salvata
    for watch in Watch.objects.all():
        if watch.likes.filter(username = request.user.username).exists():
            if watch.maison not in maison_like:
                maison_like.append(watch.maison)
                watch_like.append(watch.pk)
        if watch.maison in maison_like and watch.pk not in watch_like:
            sugg_watch.append(watch)
        if w_price + 500 > watch.price or watch.price < w_price - 500:
            watch_price.append(watch)


    context = {
        'sugg_watch':sugg_watch[:3],
        'watch_price':watch_price[:2]
    }

    return render(request, 'blog/blogPost/suggestion.html', context)

blog/templates/blog/blogPost/base_list.html
{% extends 'home_base.html' %}
{% block list_title %}{% endblock %}

{% block content %}
    <h2>{% block content_title %}{% endblock %}</h2>
    <ul class="contenitore">
        {% block object %}{% endblock %}
    </ul>
{% endblock %}

blog/templates/blog/blogPost/condition_list.html
{% extends 'blog/blogPost/base_list.html' %}

{% block list_title %}Watch List{% endblock %}
{% block content_title %}Categorie di Orologi{% endblock %}


{% block object %}
    {% for item in condition_watch_list %}
            <a href="{% url 'blog:conditionWatch' item %}">
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <h3 style="text-transform: uppercase">{{ item }}</h3>
                    {% if item.condition == 'New' %}
                        <p>Lista di tutti gli orologi in vendita che come condizione sono nuovi. All'interno troverai anche orologi venduti da privati ma mai utilizzati.</p>
                    {% endif %}
                    {% if item.condition == 'Used' %}
                        <p>Lista di tutti gli orologi in vendita che come condizione sono usati.</p>
                    {% endif %}
                    {% if item.condition == 'Vintage' %}
                        <p>Lista di tutti gli orologi in vendita Vintage. Ricordiamo che un vintage può essere anche in condizioni ottime. </p>
                    {% endif %}
                </li>
            </a>
    {% endfor %}
{% endblock %}

blog/templates/blog/blogPost/detail.html
{% extends 'home_base.html' %}

{% block title %}Watch: {{ object.model }}{% endblock %}

{% block infosite %}
    <div class="search">
        <div class="block-search">
            <ul class="contenitore">
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <a href="{% url 'blog:MaisonDetail' object.maison.pk %}"><h5>{{ object.maison }}</h5></a>
                    <h6><b>Model:</b> {{ object.model }}</h6>
                    <p><b>Reference:</b> {{ object.reference }}</p>
                    <p><b>Movement:</b> {{ object.movement }}</p>
                    <hr>
                    {% if user.is_authenticated %}
                        <p><b>Venditore: </b>{{ object.owner }}</p>
                        <p><b>State of Watch:</b> {{ object.condition }}</p>
                        <p><b>Price:</b> {{ object.price }}€</p>
                        <form class="form1">
                            <button type="button" class="btnBuy btn-primary">Procedi all'acquisto</button>
                        </form>
                        <img id="img-payment" src="/static/image/googlepay-applepay-wifi-mastercard.png" alt="pagamento">
                    {% endif %}
                </li>
            </ul>
        </div>

        <div class="block-img rounded-3 rounded">
            <img src="{{ watch.photo.url }}" alt="casey-connell">
            {% if user.is_authenticated %}
                <form action="{% url 'blog:like_post' watch.id %}" method='POST' class="form1">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary" name="post_id" value="{{ watch.id }}">Like</button>
                    {% if user.id == watch.owner.id %}
                        <a href="{% url 'blog:blogPostUpdate' watch.id %}"><button type="button" class="btn btn-outline-success">Edit</button></a>
                    {% endif %}
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

blog/templates/blog/blogPost/favorite.html
{% extends 'blog/blogPost/base_list.html' %}

{% block list_title %}Watch List{% endblock %}
{% block content_title %}Tutti gli orologi a cui hai messo mi piace{% endblock %}


{% block object %}
    {% for watch in list_like %}
            <a href="{% url 'blog:blogPostDetail' watch.pk %}">
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <img id="orologi_foto" src="{{ watch.photo.url }}" height="60%" width="auto">
                    <hr>
                    <h4>{{ watch.maison }}</h4>
                    <h6>{{ watch.model }}</h6>
                </li>
            </a>
    {% endfor %}

{% endblock %}

blog/templates/blog/blogPost/home_view.html
{% extends 'blog/blogPost/base_list.html' %}

{% block list_title %}Watch List{% endblock %}
{% block content_title %}Tutti gli orologi presenti sul sito{% endblock %}


{% block object %}
    <li class="shadow-lg p-3 mb-5 bg-body">
        <form method="GET">
            <label for="order"> Ordina per: </label>
            <select class="form-select" name="order" id="order">
                <option value="maison"> Maison </option>
                <option value="model"> Model </option>
                <option value="owner"> Proprietario </option>
            </select>
            <!-- valore del select box rimane quello selezionato -->
            <script type="text/javascript">
                document.getElementById('order').value = "{{request.GET.order}}";
            </script>
            <input class="btn btn-primary btn-lg" type="submit" style="width: auto;">
        </form>
    </li>
    {% for watch in object_list %}
        <a href="{% url 'blog:blogPostDetail' watch.pk %}">
            <li class="shadow-lg p-3 mb-5 bg-body">
                <img id="orologi_foto" src="{{ watch.photo.url }}" height="185" width="153" alt="sans">
                <hr>
                <h4>{{ watch.maison }}</h4>
                <h6>{{ watch.model }}</h6>
            </li>
        </a>
    {% endfor %}

{% endblock %}

blog/templates/blog/blogPost/insert_watch.html
{% extends 'home_base.html' %}
{% load crispy_forms_filters %}

{% block title %}Vendi un orologio{% endblock %}

{% block infosite %}
    <ul class="contenitore2">
        <li class="shadow-lg p-3 mb-5 bg-body" id="cont">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <hr/>
                <input class="btn btn-primary btn-lg" type="submit" value="Inserisci">
            </form>
        </li>
    </ul>
{% endblock %}

blog/templates/blog/blogPost/maison_create.html
{% extends 'home_base.html' %}
{% load crispy_forms_filters %}

{% block title %}Inserisci una nuova Maison{% endblock %}

{% block infosite %}
    <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Inserisci">
        </form>
{% endblock %}

blog/templates/blog/blogPost/maison_detail.html
{% extends 'home_base.html' %}

{% block content %}
    <div class="">
        <div class="">
            <h3>Orologi {{ maison }} presenti sul sito</h3>
        </div>
    </div>
    <div class="">
        <ul class="contenitore">
            {% for watch in  maison.watch_set.all %}
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <img id="orologi_foto" src="{{ watch.photo.url }}" height="185" width="153" alt="sans">
                    <hr>
                    <h4>{{ watch.maison }}</h4>
                    <h6>{{ watch.model }}</h6>
                </li>
            {% empty %}
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <h3>Non sono stati caricati ancora orologi {{ maison }}</h3>
                </li>
            {% endfor %}
        </ul>
    </div>
    <hr/>

{% endblock content %}

blog/templates/blog/blogPost/maison_list.html
{% extends 'home_base.html' %}
{% load crispy_forms_filters %}

{% block title %}Lista Maison{% endblock %}

{% block infosite %}


    <div class="row m-3 justify-content-center">
        <div class="col-md-6 text-center">
            <h3> Elenco delle maison sul sito </h3>
        </div>
    </div>
    <hr/>
    <div class="row m-3 justify-content-left">
            <ul class="contenitore3">
                {% for maison in maison_list %}
                    <a href="{% url 'blog:MaisonDetail' maison.pk %}">
                        <li class="shadow-lg p-3 mb-5 bg-body">
                            <h3>{{ maison }}</h3>
                        </li>
                    </a>
                {% endfor %}
            </ul>
        </div>

{% endblock %}

blog/templates/blog/blogPost/suggestion.html
{% extends 'blog/blogPost/base_list.html' %}

{% block list_title %}Watch List{% endblock %}
{% block content_title %}Gli orologi che ti consigliamo{% endblock %}


{% block object %}

    {% for watch in sugg_watch %}
            <a href="{% url 'blog:blogPostDetail' watch.pk %}">
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <img id="orologi_foto" src="{{ watch.photo.url }}" height="60%" width="auto">
                    <hr>
                    <h4>{{ watch.maison }}</h4>
                    <h6>{{ watch.model }}</h6>
                </li>
            </a>
    {% endfor %}
{% endblock %}

blog/templates/blog/blogPost/update_watch.html
{% extends 'home_base.html' %}
{% load crispy_forms_filters %}

{% block title %}Aggiorna il tuo orologio{% endblock %}

{% block infosite %}
    <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <hr/>
            <input type="submit" value="Aggiorna">
        </form>
{% endblock %}

blog/templates/blog/blogPost/watch_list.html
{% extends 'blog/blogPost/base_list.html' %}

{% block list_title %}Watch List{% endblock %}
{% block content_title %}Orologi presenti sul sito{% endblock %}


{% block object %}     <li class="shadow-lg p-3 mb-5 bg-body">
    <form method="GET">
        <label for="order"> Ordina per: </label>
        <select class="form-select m-2 text-center" name="order" id="order">
            <option value="maison"> Maison </option>
            <option value="model"> Model </option>
            <option value="owner"> Proprietario </option>
        </select>
        <!-- valore del select box rimane quello selezionato -->
        <script type="text/javascript">
            document.getElementById('order').value = "{{request.GET.order}}";
        </script>
        <input class="btn btn-primary btn-lg" type="submit" style="width: auto">
    </form>
     </li>
    {% for watch in condition_watch %}
        <a href="{% url 'blog:blogPostDetail' watch.pk %}">
            <li class="shadow-lg p-3 mb-5 bg-body">
                <img id="orologi_foto" src="{{ watch.photo.url }}" height="60%" width="auto">
                <hr>
                <h4>{{ watch.maison }}</h4>
                <h6>{{ watch.model }}</h6>
            </li>
        </a>
    {% endfor %}

{% endblock %}

blog/templates/blog/blogPost/watch_search.html
{% extends 'home_base.html' %}

{% block list_title %}Watch{% endblock %}
{% block content_title %}{% endblock %}


{% block content %}
    {% if searched %}
        <h3>You Searched For {{ searched }} </h3>
        <hr/>
        <ul class="contenitore">
        {% for watch in watch_list %}
            <a href="{% url 'blog:blogPostDetail' watch.pk %}">
                <li class="shadow-lg p-3 mb-5 bg-body">
                    <img id="orologi_foto" src="{{ watch.photo.url }}" height="60%" width="auto">
                    <hr>
                    <h4>{{ watch.maison }}</h4>
                    <h6>{{ watch.model }}</h6>
                </li>
            </a>
        {% endfor %}
        </ul>
    {% else %}
        <h1>Errore di ricerca</h1>
    {% endif %}

{% endblock %}