Watch_Hub/urls.py
from django.contrib import admin
from django.urls import include, path


from Watch_Hub.views import Maintenance, Home
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='Watch-Hub-Home'),
    path('manutenzione/', Maintenance.as_view(), name="maintenance"),
    path('blog/', include('blog.urls')),
    path('register/', user_views.register, name='user-create'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

blog/urls.py
from django.urls import path
from django.views.generic import UpdateView

from . import views
from blog.views import WatchDetail, WatchList, create_watch, ConditionView, LikeView, watchSearch, UpdateWatch, \
    MaisonListView, MaisonDetailView

app_name = 'blog'

urlpatterns = [
    path('<int:pk>/detail/', WatchDetail.as_view(), name="blogPostDetail"),
    path('list/', WatchList.as_view(), name="blogPostList"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('update/<int:pk>/', UpdateWatch.as_view(), name="blogPostUpdate"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('insert/', views.create_watch, name="blogPostCreate"),
    path('like/<int:pk>', LikeView, name="like_post"),
    path('search/', views.watchSearch, name="watchSearch"),
    path('condizione/<str:condition>', ConditionView, name="conditionWatch"),
    path('categoria_watch/', views.conditionListView, name='conditionWatchList'),
    path('maison_list/', MaisonListView.as_view(), name='MaisonList'),
    path('maison_detail/<int:pk>/', MaisonDetailView.as_view(), name='MaisonDetail'),
    path('favorite/', views.favorite_watch_view, name='favoriteWatch'),
    path('suggestion/', views.watch_suggestion, name='suggestionWatch'),
]

templates/Maintenance.html
<!doctype html>

<html lang="en">
    <head>
        <title>Site Of Maintenance</title>
    </head>
    <body>
        <h1>Maintenance</h1>
        <p>This site is in maintenance</p>

    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" />
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
	<!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
            crossorigin="anonymous">
    </script>
    <a href="{% url 'Watch-Hub-Home' %}">
        <h1>WATCH HUB</h1>
    </a>

    {% block header %}{% endblock %}

    {% block navbar %}{% endblock %}

    {% block search %} {% endblock %}

    {% block content %}{% endblock %}

    {% block infosite %}{% endblock %}

    {% block favorite %}{%  endblock %}

    {% block footer %}{% endblock %}
</body>
</html>

templates/home_base.html
{% extends 'base.html' %}


{% block header %}
{% endblock %}
{% block navbar %}
    <div class="nav_bar">
        <hr>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link dropdown-toggle nav_bar"
                   data-bs-toggle="dropdown"
                   href="#"
                   role="button"
                   aria-expanded="false"
                   style="color:black">ACQUISTA UN OROLOGIO</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'blog:MaisonList' %}">Maison</a></li>
                    <li><a class="dropdown-item" href="{% url 'blog:conditionWatchList' %}">Categoria</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class ="dropdown-item" href="{% url 'blog:blogPostList' %}">Tutti</a></li>
                    {% for item in cat_menu %}
                        <li><a class="dropdown-item" href="{% url 'blog:conditionWatch' item %}">{{ item }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   data-bs-toggle="dropdown"
                   href="#"
                   role="button"
                   aria-expanded="false"
                   style="color:black">VENDI UN OROLOGIO</a>
                <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'blog:blogPostCreate' %}">{{ user.username }} Vendi Da Privato</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'user-create' %}">Registrati Per Vendere</a></li>
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login Per Vendere</a></li>
                    {% endif %}
                </ul>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:favoriteWatch' %}" style="color:black">I MIEI OROLOGI PREFERITI</a>
                </li>
            {% endif %}
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}" style="color:black; text-transform: uppercase">LOGIN</a>
                </li>
            {% endif %}


        </ul>
        <hr>
    </div>
{% endblock %}


{% block search %}{% endblock %}

{% block content %}{% endblock %}

{% block infosite %}{% endblock %}

{% block favorite %}{%  endblock %}

{% block footer %}
    <footer class="foo">
        <hr>
        <ul class="fooul">
            <li id="item5" style="margin-top: 1%;">
                <img src="/static/image/icons8-persona-di-sesso-maschile-30.png" alt="icon"/>
                <p>DANIL LUGLI, UNIMORE, matr. 128504</p>
            </li>
            <li id="item6">
                <a id="a1" href="#">Chi siamo</a>
                <a id="a2" href="{% url 'Watch-Hub-Home' %}">Home</a>
            </li>
        </ul>
    </footer>
{% endblock %}

templates/home_extend.html
{% extends 'home_base.html' %}
{% load static %}

{% block title %}Watch Hub{%  endblock %}

{% block search %}
    <div class="search">
        <div class="block-search">
            <h5>Scegli tra tutti gli orologi esistenti in vendita.</h5>
            <h3>CERCA IL MODELLO DEI TUOI SOGNI</h3>
            <h6>Cerca, trova e acquista! I venditori sono tutti verificati dal nostro sito. </h6>
            <form class="form1" method=POST action="{% url 'blog:watchSearch' %}">
                {% csrf_token %}
                <input class="input-search rounded-end" type="search" placeholder="Scrivi il modello del tuo orologio..." aria-label="Cerca" name="searched">
                <button type="submit" class="btn btn-primary rounded-start" style="margin-top: 0px;">Cerca</button>
            </form>
        </div>

        <div class="block-img rounded-3 rounded">
            <img src="/static/image/casey-connell-wGeNkndPSn4-unsplash.jpg" id="foto_home" alt="casey-connell">
        </div>
    </div>
{% endblock %}


{% block infosite %}
    <h2>SCOPRI IL NOSTRO POTENZIALE</h2>
    <h5>Registrati o Accedi per avere tutte le funzionalità</h5>
    <ul class="contenitore info">
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}">
                <li class="info-item shadow-lg p-3 mb-5 bg-body">
                    <img src="/static/image/1F9D1-1F3FB_color.png" alt="persona">
                    <h3>LOGIN</h3>
                    <p>Accedi per comprare l'orologio dei tuoi sogni</p>
                </li>
            </a>
        {% else %}
            <a href="{% url 'profile' %}">
                <li class="info-item shadow-lg p-3 mb-5 bg-body">
                    <img src="/static/image/1F9D1-1F3FB_color.png" alt="persona">
                    <h3>{{ user.username }}</h3>
                    <p>Hai effettuato l'accesso, clicca qui per andare al tuo profilo</p>
                </li>
            </a>
        {% endif %}
        {% if not user.is_authenticated %}
        <a href="{% url 'user-create' %}">
            <li class="info-item shadow-lg p-3 mb-5 bg-body">
                <img src="/static/image/1F512_color.png" alt="lucchetto">
                <h3>REGISTRATI</h3>
                <p>Per avere più funzionalità</p>
            </li>
        </a>
    {% else %}
            <a href="{% url 'blog:favoriteWatch' %}">
            <li class="info-item shadow-lg p-3 mb-5 bg-body">
                <img src="/static/image/1F512_color.png" alt="lucchetto">
                <h3>I TUOI OROLOGI PREFERITI</h3>
                <p>Visualizza tutti i tuoi orologi preferiti</p>
            </li>
        </a>
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'blog:suggestionWatch' %}">
            <li class="info-item shadow-lg p-3 mb-5 bg-body">
                <img src="/static/image/1F4BC_color.png" alt="valigetta">
                <h3>OROLOGI CONSIGLIATI</h3>
                <p>Orologi consigliati per {{ user.username }}</p>
            </li>
        </a>
    {% endif %}
    </ul>
    </div>
{% endblock %}

{% block favorite %}
    <div class="div shadow p-3 mb-5 bg-white">
        <h2>GUARDA TUTTI GLI OROLOGI PRESENTI SUL SITO</h2>
        <h5>Tutti gli orologi all'interno del sito sono di proprietà di utenti verificati da noi di Watch Hub.</h5>
        <ul class="contenitore">
            <a href="{% url 'blog:blogPostList' %}">
                <button type="button" class=" btn btn-primary btn-lg" style="width: auto;">OROLOGI</button>
            </a>

        </ul>
    </div>
{% endblock %}